In [61]:
import os
import pandas as pd
import numpy as np
import joblib
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.impute import SimpleImputer
import warnings

warnings.filterwarnings('ignore')
os.makedirs('data/processed', exist_ok=True)
os.makedirs('models', exist_ok=True)

In [62]:
data = pd.read_csv('/home/pratham/Disk2/Projects/ml_projects/loan_prediction/data/raw/loan_data.csv')

In [63]:
data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [64]:
data.drop('Loan_ID', axis=1, inplace=True)

In [65]:
data

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
609,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [66]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Gender             601 non-null    str
 1   Married            611 non-null    str
 2   Dependents         599 non-null    str
 3   Education          614 non-null    str
 4   Self_Employed      582 non-null    str
 5   ApplicantIncome    614 non-null    int64
 6   CoapplicantIncome  614 non-null    float64
 7   LoanAmount         592 non-null    float64
 8   Loan_Amount_Term   600 non-null    float64
 9   Credit_History     564 non-null    float64
 10  Property_Area      614 non-null    str
 11  Loan_Status        614 non-null    str
dtypes: float64(4), int64(1), str(7)
memory usage: 57.7 KB

In [67]:
cat_cols = ['Gender', 'Married', 'Dependents', 'Self_Employed']
num_cols = ['LoanAmount', 'Loan_Amount_Term', 'Credit_History']

In [68]:
data.isnull().sum()

Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [69]:
# Impute Categorical Features
cat_imputer = SimpleImputer(strategy='most_frequent')
data[cat_cols] = cat_imputer.fit_transform(data[cat_cols])

In [70]:
# Impute Numerical Features
num_imputer = SimpleImputer(strategy='median')
data[num_cols] = num_imputer.fit_transform(data[num_cols])

In [71]:
data

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,Male,No,0,Graduate,No,5849,0.0,128.0,360.0,1.0,Urban,Y
1,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
609,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [72]:
data.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

# Cell 5: Feature Engineering

In [73]:
data['Dependents'] = data['Dependents'].replace('3+', 3).astype(int)

data['Total_Income'] = data['ApplicantIncome'] + data['CoapplicantIncome']

data['EMI'] = (data['LoanAmount'] * 1000) / data['Loan_Amount_Term']

In [74]:
data[['ApplicantIncome', 'CoapplicantIncome', 'Total_Income', 'LoanAmount', 'Loan_Amount_Term', 'EMI']].head()

,ApplicantIncome,CoapplicantIncome,Total_Income,LoanAmount,Loan_Amount_Term,EMI
0,5849,0.0,5849.0,128.0,360.0,355.555556
1,4583,1508.0,6091.0,128.0,360.0,355.555556
2,3000,0.0,3000.0,66.0,360.0,183.333333
3,2583,2358.0,4941.0,120.0,360.0,333.333333
4,6000,0.0,6000.0,141.0,360.0,391.666667

In [75]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Gender             614 non-null    str
 1   Married            614 non-null    str
 2   Dependents         614 non-null    int64
 3   Education          614 non-null    str
 4   Self_Employed      614 non-null    str
 5   ApplicantIncome    614 non-null    int64
 6   CoapplicantIncome  614 non-null    float64
 7   LoanAmount         614 non-null    float64
 8   Loan_Amount_Term   614 non-null    float64
 9   Credit_History     614 non-null    float64
 10  Property_Area      614 non-null    str
 11  Loan_Status        614 non-null    str
 12  Total_Income       614 non-null    float64
 13  EMI                614 non-null    float64
dtypes: float64(6), int64(2), str(6)
memory usage: 67.3 KB

In [76]:
encoders = ['Gender', 'Married', 'Education', 'Self_Employed', 'Property_Area', 'Loan_Status']
le_dict = {}
for col in encoders:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    le_dict[col] = le
    
joblib.dump(le_dict, '/home/pratham/Disk2/Projects/ml_projects/loan_prediction/models/label_encoders.pkl')

['/home/pratham/Disk2/Projects/ml_projects/loan_prediction/models/label_encoders.pkl']

In [77]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Gender             614 non-null    int64
 1   Married            614 non-null    int64
 2   Dependents         614 non-null    int64
 3   Education          614 non-null    int64
 4   Self_Employed      614 non-null    int64
 5   ApplicantIncome    614 non-null    int64
 6   CoapplicantIncome  614 non-null    float64
 7   LoanAmount         614 non-null    float64
 8   Loan_Amount_Term   614 non-null    float64
 9   Credit_History     614 non-null    float64
 10  Property_Area      614 non-null    int64
 11  Loan_Status        614 non-null    int64
 12  Total_Income       614 non-null    float64
 13  EMI                614 non-null    float64
dtypes: float64(6), int64(8)
memory usage: 67.3 KB

In [78]:
data

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,Total_Income,EMI
0,1,0,0,0,0,5849,0.0,128.0,360.0,1.0,2,1,5849.0,355.555556
1,1,1,1,0,0,4583,1508.0,128.0,360.0,1.0,0,0,6091.0,355.555556
2,1,1,0,0,1,3000,0.0,66.0,360.0,1.0,2,1,3000.0,183.333333
3,1,1,0,1,0,2583,2358.0,120.0,360.0,1.0,2,1,4941.0,333.333333
4,1,0,0,0,0,6000,0.0,141.0,360.0,1.0,2,1,6000.0,391.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,0,0,0,0,0,2900,0.0,71.0,360.0,1.0,0,1,2900.0,197.222222
610,1,1,3,0,0,4106,0.0,40.0,180.0,1.0,0,1,4106.0,222.222222
611,1,1,1,0,0,8072,240.0,253.0,360.0,1.0,2,1,8312.0,702.777778
612,1,1,2,0,0,7583,0.0,187.0,360.0,1.0,2,1,7583.0,519.444444
613,0,0,0,0,1,4583,0.0,133.0,360.0,0.0,1,0,4583.0,369.444444

In [79]:
x = data.drop('Loan_Status', axis=1)
y = data['Loan_Status']

In [80]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42,stratify=y)

In [81]:
x_train.shape, x_test.shape

((491, 13), (123, 13))

In [82]:
data.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status',
       'Total_Income', 'EMI'],
      dtype='str')

In [83]:
data

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,Total_Income,EMI
0,1,0,0,0,0,5849,0.0,128.0,360.0,1.0,2,1,5849.0,355.555556
1,1,1,1,0,0,4583,1508.0,128.0,360.0,1.0,0,0,6091.0,355.555556
2,1,1,0,0,1,3000,0.0,66.0,360.0,1.0,2,1,3000.0,183.333333
3,1,1,0,1,0,2583,2358.0,120.0,360.0,1.0,2,1,4941.0,333.333333
4,1,0,0,0,0,6000,0.0,141.0,360.0,1.0,2,1,6000.0,391.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,0,0,0,0,0,2900,0.0,71.0,360.0,1.0,0,1,2900.0,197.222222
610,1,1,3,0,0,4106,0.0,40.0,180.0,1.0,0,1,4106.0,222.222222
611,1,1,1,0,0,8072,240.0,253.0,360.0,1.0,2,1,8312.0,702.777778
612,1,1,2,0,0,7583,0.0,187.0,360.0,1.0,2,1,7583.0,519.444444
613,0,0,0,0,1,4583,0.0,133.0,360.0,0.0,1,0,4583.0,369.444444

In [84]:
scaler = StandardScaler()

scale_cols = ['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term', 'Total_Income', 'EMI']

x_train[scale_cols] = scaler.fit_transform(x_train[scale_cols])
x_test[scale_cols] = scaler.transform(x_test[scale_cols])

In [85]:
x_train.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Total_Income,EMI
154,1,0,0,0,0,-0.352802,-0.563228,-1.131588,0.280691,1.0,2,-0.575168,-0.620918
239,1,1,1,0,0,-0.343346,-0.563228,-0.592309,0.280691,1.0,1,-0.566044,-0.391569
448,1,1,2,0,0,-0.339471,0.050405,0.040758,0.280691,0.0,0,-0.306544,-0.122334
471,1,1,1,1,0,-0.445963,-0.024953,-0.393010,-2.486768,0.0,0,-0.440706,0.256589
273,1,1,0,0,0,-0.451078,0.234495,0.040758,0.280691,1.0,1,-0.337505,-0.122334

In [86]:
joblib.dump(scaler, '/home/pratham/Disk2/Projects/ml_projects/loan_prediction/models/scaler.pkl')

['/home/pratham/Disk2/Projects/ml_projects/loan_prediction/models/scaler.pkl']

In [87]:
x_train.to_csv('/home/pratham/Disk2/Projects/ml_projects/loan_prediction/data/processed/x_train.csv', index=False)
x_test.to_csv('/home/pratham/Disk2/Projects/ml_projects/loan_prediction/data/processed/x_test.csv', index=False)
y_train.to_csv('/home/pratham/Disk2/Projects/ml_projects/loan_prediction/data/processed/y_train.csv', index=False)
y_test.to_csv('/home/pratham/Disk2/Projects/ml_projects/loan_prediction/data/processed/y_test.csv', index=False)